// Default avatar as 100x100 base64 JPEG
// This will be generated by the client-side utility
export const DEFAULT_AVATAR = 'null_profile.jpg'; // Placeholder until we generate the actual base64

// Utility function to generate the default avatar from null_profile.jpg
export async function generateDefaultAvatar(): Promise<string> {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d');
      
      // Set canvas to 100x100
      canvas.width = 100;
      canvas.height = 100;
      
      if (ctx) {
        // Draw the image resized to 100x100
        ctx.drawImage(img, 0, 0, 100, 100);
        // Convert to base64 JPEG
        const base64 = canvas.toDataURL('image/jpeg', 0.8);
        resolve(base64);
      } else {
        resolve('null_profile.jpg');
      }
    };
    
    img.onerror = () => {
      resolve('null_profile.jpg');
    };
    
    // Load the null_profile.jpg from the public folder
    img.src = '/null_profile.jpg';
  });
}
